[colors.bright]
black = "0x75715e"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf9f8f5"
yellow = "0xf4bf75"

[colors.normal]
black = "0x272822"
blue = "0x66d9ef"
cyan = "0xa1efe4"
green = "0xa6e22e"
magenta = "0xae81ff"
red = "0xf92672"
white = "0xf8f8f2"
yellow = "0xf4bf75"

[colors.primary]
background = "0x272822"
foreground = "0xf8f8f2"

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
opacity = 1.0

[window.padding]
x = 5
y = 7
